<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMtwB5tx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMtwB5tx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMtwB5tx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMtwB5tx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMtwB5tx\App_KernelDevDebugContainer([
    'container.build_hash' => 'MtwB5tx',
    'container.build_id' => 'bb06229e',
    'container.build_time' => 1637163219,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMtwB5tx');
