<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIeWcaPh\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIeWcaPh/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIeWcaPh.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIeWcaPh\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIeWcaPh\App_KernelDevDebugContainer([
    'container.build_hash' => 'IeWcaPh',
    'container.build_id' => 'da41adf0',
    'container.build_time' => 1649060963,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIeWcaPh');
